name: build-website
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Init
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn
      - name: Build
      - run: yarn build
      - name: Add Assets
      - run: cp assets/* docs
      - name: Stage Files
        run: git add -f docs
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Build for deploy"
      - name: Publish
        run: |
          git subtree split --prefix docs -b gh-pages
          git push -f origin gh-pages:gh-pages
